openapi: 3.0.1
info:
  title: generator
  description: generator
  version: '0.1'
paths:
  /:
    get:
      description: generate composed name
      operationId: generateName
      tags:
        - generator
      responses:
        '200':
          description: a randomly composed name
      servers:
        - url: 'http://generator:80'

