openapi: 3.0.1
info:
  title: generator
  description: generator
  version: '0.1'
servers:
  - url: http://sentence.dev/sentence
    description: Development server
paths:
  /sentence:
    get:
      description: generate composed name
      operationId: generateName
      tags:
        - generator
      responses:
        '200':
          description: a randomly composed name
