openapi: 3.0.1
info:
  title: animals
  description: animal DB
  version: '0.1'
servers:
  - url: http://animals/v0.1
    description: Development server
paths:
  /animals:
    get:
      description: List all animals
      operationId: listAnimals
      tags:
        - animals
      responses:
        '200':
          description: a list of animals with their index
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Animals"
              #examples: {"animals": [{"id":1,"name":"lion"}]}
    post:
      description: create an animal
      operationId: createAnimal
      tags:
        - animals
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: integer
            examples:
              '0':
                value: '{"name":"cat"}'
              '1':
                value: '{"id":2}'
      responses:
        '201':
          description: animal created
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
    delete:
      description: delete an adjective
      operationId: deleteAnimal
      tags:
        - adjectives
      responses:
        '404':
          description: Delete an Adjective
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
  /animals/{id}:
    get:
      description: get a specific adjective
      operationId: showAnimalsById
      tags:
        - animals
      parameters:
        - name: id
          in: path
          required: true
          description: id of the animal to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Animal"
              # examples: {"adjectives": [{"id":1,"name":"lion"}]}
components:
  schemas:
    Animal:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
    Animals:
      type: array
      items:
        $ref: "#/components/schemas/Animal"
