openapi: 3.0.1
info:
  title: generator
  description: generator
  version: '0.1'
servers:
  - url: http://generator/v0.1
    description: Development server
paths:
  /:
    get:
      description: generate composed name
      operationId: generateName
      tags:
        - generator
      responses:
        '200':
          description: a randomly composed name
